### ISSUE TITLE
`CellIndex` to `NonZeroU64`

### ISSUE THREAD

**Issue by juanCortelezzi** [HydroniumLabs/h3o#11]
I am in need of getting the id of the cell as a u64 or NonZeroU64 to make some bit calculations but I can not find the way to do it (please let me know if there is). A way to solve my problem is to implement any of the following methods for `CellIndex`:
```rs
use std::num::NonZeroU64;

struct CellIndex(NonZeroU64);

impl CellIndex {
    const fn to_u64(&self) -> u64 {
        self.0.get()
    }

    const fn to_inner(&self) -> NonZeroU64 {
        self.0
    }
}

fn main() {
    let cell_id = 0x83c2e3fffffffff;
    let cell_id_non_zero = NonZeroU64::new(cell_id).unwrap();
    let cell = CellIndex(cell_id_non_zero);

    assert_eq!(cell_id_non_zero, cell.to_inner());
    assert_eq!(cell_id, cell.to_u64());
}
```

The naming of the functions is not my best but it does the job. Anyways, thank you very much for this library, we all know that a rewrite in Rust is always necessary. Also, I am more than happy to open a PR if you are ok with that.

**Comment by grim7reaper** [comment]
`CellIndex` implements the `From/Into` traits for `u64` so you can write:

```rust
let cell_value = u64::from(cell_index);
```

Which kind of bit calculation do you need?
(to see if it would make sense to expose them in the API or if it's too niche)

**Comment by juanCortelezzi** [comment]
Well, how did I not see that? 

I was writing a test program that filtered a Vec of h3-cells depending on which series of hexagons they belong to, thought that bitmasking could help me do that. Thanks for your time!
