### ISSUE TITLE
to_geom crashes on coords.len() assert

### ISSUE THREAD

**Issue by evavh** [HydroniumLabs/h3o#12]
I am trying to convert a large number of CellIndexes to Multipolygons, to be able to efficiently plot them on a map. On certain lists of CellIndexes, however, the function to_geom crashes on an assert statement:
`thread 'main' panicked at 'assertion failed: coords.len() >= 4', [...]/h3o-0.3.1/src/geom/vertex_graph.rs:169:13`

[This repo](https://github.com/evavh/h3o-polygon-conversion-crash) contains a minimal example for this issue. I have only been able to narrow the list of CellIndexes down to about 100k items, by generating a grid disk around the coordinates that the assert fails on. I have another example as well, but that one only crashes when converting 1.6 million CellIndexes (!) around the coordinates that fail the assert statement.

It thus seems the crash only happens when converting a lot of hexagons around the coordinates that it actually crashes on. Partitioning the list of cells into more naive chunks of various sizes, and converting those using to_geom, does not cause a crash.

It seems to me that the function to_geom should work for any Iterator of CellIndexes, no matter the size, as long as memory is sufficient (which it is, in this case). I therefore think i have stumbled upon some strange edge case in the algorithm that performs the conversion.

**Comment by grim7reaper** [comment]
Thanks for the report.

Bugs in this area are usually a bit hard to troubleshoot, so I'm glad that you took the time to provide an input that trigger the assert, this will help a lot 🙏 

I was able to trim your input down to 4 indexes while preserving the crash:

```rust
use h3o::geom::ToGeo;
use h3o::CellIndex;

fn main() {
    let cell_indexes = vec![
        CellIndex::try_from(0x8b1f25a91526fff).unwrap(),
        CellIndex::try_from(0x8b1f2506d45dfff).unwrap(),
        CellIndex::try_from(0x8b1f25a901a1fff).unwrap(),
        CellIndex::try_from(0x8b1f25324b98fff).unwrap(),
    ];

    println!("Trying to convert CellIndexes to Multipolygon...");
    cell_indexes.to_geom(true).unwrap();
}
```

Will dig in and hopefully come up with a fix soon :)

**Comment by grim7reaper** [comment]
I've found the root cause (already fixed a similar bug a few commits ago...), now I need to find the best way to fix this.
