### ISSUE TITLE
Publish a new release with geo v0.25

### ISSUE THREAD

**Issue by nmandery** [HydroniumLabs/h3o#14]
With the release of rust 1.71 there is a [compilation issue with the `geo` crate in version <= 0.24](https://github.com/georust/geo/issues/1013). Since then geo v0.25 has been released with a fix.

In the repository h3o already uses v0.25 of `geo` while the `h3o` version released on crates.io still depends on `geo` v0.24. Maybe it makes sense to publish a new `h3o` release - at least I am running into the compilation issue caused by the dependency.

**Comment by grim7reaper** [comment]
Thanks for the heads up 🙏 

v0.3.3 have been published with the fix

**Comment by nmandery** [comment]
Thanks a lot :+1:
