### ISSUE TITLE
Convert to u64?

### ISSUE THREAD

**Issue by KMarshland** [HydroniumLabs/h3o#17]
I'm attempting to save h3 cell indexes in a database as i64s. Is there a way to convert a CellIndex to a u64 (as I can see its native representation is 64 bits already)?

Ordinarily I'd do something like:
```rust
impl CellIndex {
    pub fn to_u64(&self) -> u64 {
        self.0.get() as u64
    }
}
```

But it is of course private, being in a crate and all. If there's no existing solution, I'm happy to create a PR.

**Comment by KMarshland** [comment]
In the interim, I have found the following two workarounds. The first is unsafe but faster.
```rust
unsafe {
    *(std::mem::transmute::<&CellIndex, &NonZeroU64>(&cell_index) as *const NonZeroU64 as *const i64)
}
```

The second relies on the fact that it implements `fmt::LowerHex`
```rust
i64::from_str_radix(&format!("{:x}", cell_index).as_str(), 16).ok()
```

**Comment by grim7reaper** [comment]
Yup, there is a simple and safe way to do it 🙂
You can see my message with an example [here](https://github.com/HydroniumLabs/h3o/issues/11#issuecomment-1556117452).

**Comment by KMarshland** [comment]
Incredible -- can't believe I didn't see that. Thank you!

**Comment by grim7reaper** [comment]
You're not the first, and likely not the last.

It's true that implemented traits are a bit hidden in the generated doc, maybe I should add a more visible example.
