### ISSUE TITLE
Public coord_at version 

### ISSUE THREAD

**Issue by kurotych** [HydroniumLabs/h3o#18]
Hello. h3o has an internal function `coord_at` that "Computes the point on the sphere a specified azimuth and distance".
Is it possible to create a public version of this function to use outside? 

Currently, I use this function. But maybe it'd be nice to have such functionality built in the h3o. 

```rust
fn calculate_destination_point(lat: f64, lon: f64, azimuth: f64, length_m: f64) -> Result<LatLng> {
    // Convert azimuth to radians
    let azimuth_rad = azimuth.to_radians();

    // Convert latitude and longitude to radians
    let lat1_rad = lat.to_radians();
    let lon1_rad = lon.to_radians();

    // Calculate the destination point's latitude
    let lat2_rad = (lat1_rad.sin() * (length_m / EARTH_RADIUS).cos()
        + lat1_rad.cos() * (length_m / EARTH_RADIUS).sin() * azimuth_rad.cos())
    .asin();

    // Calculate the destination point's longitude
    let lon2_rad = lon1_rad
        + (azimuth_rad.sin() * (length_m / EARTH_RADIUS).sin() * lat1_rad.cos())
            .atan2((length_m / EARTH_RADIUS).cos() - lat1_rad.sin() * lat2_rad.sin());

    // Convert the destination latitude and longitude back to degrees
    let lat2 = lat2_rad.to_degrees();
    let lon2 = lon2_rad.to_degrees();
    Ok(LatLng::new(lat2, lon2)?)
}
```

**Comment by grim7reaper** [comment]
Hello,

As you said, it's an internal function used for some internal calculations, so I'm not sure if it deserves to be part of the public API (with all the implications it brings) of h3o.

What is your use case?

Similarly, we currently have the `LatLng::distance` functions that kinda stand out...
If it weren't for the API compatibility with the C library they wouldn't exists in h3o.

IMHO, those kind of functions (not related to H3 per se) better fit in more generic geospatial library, like [geo](https://docs.rs/geo/latest/geo/index.html) (e.g. for [destination point](https://docs.rs/geo/latest/geo/algorithm/geodesic_destination/index.html)).

**Comment by kurotych** [comment]
Hello, thank you for your answer. 

> What is your use case?

My case described in presented function. I have: a point on the map (lat/l&t), azimuth, length and I need to calculate the second point. 

[destination point](https://docs.rs/geo/latest/geo/algorithm/geodesic_destination/index.html) - It is exactly what I need. sorry for bothering you, thank you!
