### ISSUE TITLE
Support no_std

### ISSUE THREAD

**Issue by LegNeato** [HydroniumLabs/h3o#19]
For embedded and rust-gpu, it would be nice to  have std be an optional feature that is turned on by default.

I'm not sure if this is possible / how much standard is needed but from a high level it appears to be a lot of math and lookup tables.

**Comment by grim7reaper** [comment]
Agreed

That's something I wanted to do at the beginning but then left on the side due to lack of time.

Outside of the geometry-related algorithms (which relies on collections and memory allocation) it should be relatively straightforward indeed.

For some functions maybe we could propose an alternative API where the caller provides preallocated memory (which is the API of the C implementation).

**Comment by LegNeato** [comment]
FWIW I poked at this a bit and found and fixed an issue with a dep on no_std:

https://github.com/carbotaniuman/auto_ops/pull/17

Not sure I'll have time to go all the way though.

**Comment by grim7reaper** [comment]
Thanks.

Any help is appreciated, and even if you don't have time to go through everything, I'll pick it up eventually 🙂 

I should have some spare time in the upcoming months, so I'll probably look either at that and/or at the new polyfill algo they implemented recently (I'm curious to see how it performs compared to my optimized version of the current algo

**Comment by grim7reaper** [comment]
Little update: I have a working `no_std` version 😀 
100% of the core library is available, but the optional `geo` feature still requires `std` (as I expected).
It may be possible to lift this restriction in the future, but that's a way bigger task as it involves either having a `no_std` version of the Rust geo library (or re-implementing the subset of functions I need, but I would rather avoid this...).

The code still need a little bit of cleanup & documentation, but it's looking good 🙂
It will likely land in the following weeks.

And about that:
> it appears to be a lot of math

Surprisingly enough, this proved to be an hindrance :sweat_smile:

**Comment by LegNeato** [comment]
Wow, that was quick!

**Comment by grim7reaper** [comment]
Yay, on one hand it was way easier than expected (thanks to the `alloc` crate mainly).

On the other hand, the lack of math functions in `core` was unexpected and added some extra roundabouts.
