### ISSUE TITLE
Equality to H3

### ISSUE THREAD

**Issue by yiftachn** [HydroniumLabs/h3o#28]
Hey! Thanks for this. 
Is it algorithmically EXACTLY the same as H3? 
Specifically, given a point and a resolution, will the H3 index will be the same?

**Comment by grim7reaper** [comment]
There are some difference in term of implementation but for a given input the output should be the same yeah 👍

Actually, a large part of the test suite ensure that h3o produces the same result as h3 (and the C binding of h3o used to pass the H3 test suite)

**Comment by yiftachn** [comment]
Amazing. Many thanks for this awsome work
