### ISSUE TITLE
Convert to lat/long & resolution from cell hex? Or from cell string? Or cell integer?

### ISSUE THREAD

**Issue by jonmdev** [HydroniumLabs/h3o#30]
H3Geo identifies locations in terms like this:

- https://h3geo.org/#hex=822ca7fffffffff

It is my understanding we then have four ways to represent a cell:

1) **String of hex:** "822ca7fffffffff"
2) **True hex:** 0x822ca7fffffffff
3) **Unsigned 64 bit Integer:** 586253552616210431
4) **Center lat-long + resolution:** Lat./Lng.: 33.81034, 44.02445, resolution: 2

I can convert from long-lat + resolution to string of hex as follows:

```
let lat_long = h3o::LatLng::new(lat, long); 

    match lat_long {
        Ok(val) => {
            let cell = val.to_cell(resolution_enum); 
            return cell.to_string();
        },
        Err(_err) => {
        }
    }
```

How would I then reverse this, and convert from the string that results "822ca7fffffffff" back to a center lat/long & resolution?

Or convert between each of these three representations of the cell: "822ca7fffffffff", 0x822ca7fffffffff, and 586253552616210431?

Thanks for any help or clarification.

**Comment by grim7reaper** [comment]
> How would I then reverse this, and convert from the string that results "822ca7fffffffff" back to a center lat/long & resolution?

You can convert a cell back into a `LatLng` like this.

```rust
let ll = h3o::LatLng::from(cell);
let resolution = cell.resolution();
```

> Or convert between each of these three representations of the cell: "822ca7fffffffff", 0x822ca7fffffffff, and 586253552616210431?

It can be done with the `TryFrom` trait for the integers, and `FromStr` for the string.

```rust
use h3o::CellIndex;

let cell1 = CellIndex::try_from(0x8a1fb46622dffff)?;
let cell2 = CellIndex::try_from(622054503267303423)?;
let cell3 =  "8a1fb46622dffff".parse::<CellIndex>()?;
```

**Comment by jonmdev** [comment]
> > How would I then reverse this, and convert from the string that results "822ca7fffffffff" back to a center lat/long & resolution?
> 
> You can convert a cell back into a `LatLng` like this, through the `From` trait. Resolution is embedded into the cell and can be extracted.
> 
> ```rust
> let ll = h3o::LatLng::from(cell);
> let resolution = cell.resolution();
> ```
> 
> > Or convert between each of these three representations of the cell: "822ca7fffffffff", 0x822ca7fffffffff, and 586253552616210431?
> 
> It can be done with the `TryFrom` trait for the integers, and `FromStr` for the string.
> 
> ```rust
> use h3o::CellIndex;
> 
> let cell1 = CellIndex::try_from(0x8a1fb46622dffff)?;
> let cell2 = CellIndex::try_from(622054503267303423)?;
> let cell3 = "8a1fb46622dffff".parse::<CellIndex>()?;
> ```

Thanks! That is great. I have just a few follow up questions (which are more about H3 and Rust admittedly, but perhaps you may know or be willing to help).

The Rust types for the three inputted cell representations in your example would be what? Ie. 
- `622054503267303423` would be a 64 bit int `i64` or `u64`. I posted asking whether a truly unsigned int is needed [here](https://github.com/uber/h3/issues/929) - do you know if it matters? ie. Can either capture the full range of possible values?
- "8a1fb46622dffff" would be a string `String`. That is obvious.
- What in Rust terms would be `0x8a1fb46622dffff`? In C++ there is actually a [hex type](https://en.cppreference.com/w/cpp/io/manip/hex). Does Rust have a type for "hex"? If you type `0x8a1fb46622dffff` is that automatically just taken as an i64 or u64 by Rust?

Thanks again.
