### ISSUE TITLE
Marking `new_unchecked` functions as unsafe

### ISSUE THREAD

**Issue by jonasspinner** [HydroniumLabs/h3o#5]
There are `new_unchecked` functions in  that expect  some form of invariant to be upheld by the caller. I think it is a good idea to mark them as unsafe to make it explicit at the call site (see: [*_unchecked in std](https://doc.rust-lang.org/stable/std/?search=_unchecked)).

## Example

Currently the following code is not marked as unsafe and results in undefined behavior:

```
let dir = h3o::direction::Direction::new_unchecked(7);
```

## Locations
BaseCell, CellIndex, Direction, DirectedEdgeIndex, Face, LatLng, LocalIJ, Resolution, Vertex and VertexIndex

<details>
<summary>See locations</summary>

https://github.com/HydroniumLabs/h3o/blob/129e80b1b33e4c3847a1a5dd65dadad11e00803f/src/base_cell.rs#L27-L30

https://github.com/HydroniumLabs/h3o/blob/129e80b1b33e4c3847a1a5dd65dadad11e00803f/src/index/cell.rs#L1228-L1231

https://github.com/HydroniumLabs/h3o/blob/129e80b1b33e4c3847a1a5dd65dadad11e00803f/src/direction.rs#L111-L115

https://github.com/HydroniumLabs/h3o/blob/129e80b1b33e4c3847a1a5dd65dadad11e00803f/src/index/edge.rs#L39-L42

https://github.com/HydroniumLabs/h3o/blob/129e80b1b33e4c3847a1a5dd65dadad11e00803f/src/face.rs#L24-L27

https://github.com/HydroniumLabs/h3o/blob/129e80b1b33e4c3847a1a5dd65dadad11e00803f/src/coord/latlng.rs#L367-L371

https://github.com/HydroniumLabs/h3o/blob/129e80b1b33e4c3847a1a5dd65dadad11e00803f/src/coord/localij.rs#L254-L258

https://github.com/HydroniumLabs/h3o/blob/129e80b1b33e4c3847a1a5dd65dadad11e00803f/src/resolution.rs#L333-L337

https://github.com/HydroniumLabs/h3o/blob/129e80b1b33e4c3847a1a5dd65dadad11e00803f/src/index/vertex.rs#L43-L46

https://github.com/HydroniumLabs/h3o/blob/129e80b1b33e4c3847a1a5dd65dadad11e00803f/src/index/vertex.rs#L185-L190
</details>

**Comment by grim7reaper** [comment]
Yeah, I've went back and forth on whether to use unsafe or not for those functions.

For most of them, they don't introduce any soundness issue/undefined behavior, so I think it's fine to keep them as-is.

The question remains for `Direction` and `Resolution`: those are indeed dangerous (even though they aren't exposed publicly).

Ideally I would like to get rid of the unsafe in these fonction (or replace the `debug_assert!` by an `assert!`), I just need to check if there is an impact on the perf or not:
- if not (or small enough) => go for it
- if there is, then yeah we could mark those two functions as unsafe.

Just need to run the benchmark suite and critcmp the results with the current version, not complicated but I need to take the time/find an idle machine to do so.

**Comment by jonasspinner** [comment]
Thanks for the response. I think that is a viable policy.

So a possible action would be to code up some benchmark and then deciding on `Direction` and `Resolution`.

**Comment by grim7reaper** [comment]
Yup, that's it.

I think the existing benchmarks are already a good starting point to gauge the impact of this change.
I can probably find some time during the week to do a complete run of the suite.
