### ISSUE TITLE
[Nonsense] About the meaning of project name

### ISSUE THREAD

**Issue by ClSlaid** [HydroniumLabs/h3o#7]
Feel free to close this issue, this issue just contains some nonsense thinking about the project names. :)

Chemically (or physically) speaking, protons ( $H^{+}$ ) in acid solutions will produce `oxonium` with water:
$$H^{+} + H_{2}O \rightarrow H_{3}O^{+}$$

https://pubchem.ncbi.nlm.nih.gov/compound/Oxonium

So you can announce that the project's name means `oxonium` proudly in the README.md.

**Comment by grim7reaper** [comment]
Yeah, IIUC oxonium is another name for the hydronium ion.

My point was more about that the backstory of the name (oxydation of H3) doesn't really match the real life reaction (protonation of water), as your equation demonstrates.

But I'm fine with it ^^
