### ISSUE TITLE
Support for arbitrary planet sizes

### ISSUE THREAD

**Issue by LegNeato** [HydroniumLabs/h3o#8]
Thank you for this library! Impressive work.

Currently the library is hard coded to Earth. It would be nice to support arbitrary planets.

To support this the area calculations could no longer be hard coded and would need to be converted to const functions to calculate, see 
https://github.com/uber/h3/issues/350.

There is a similar request in `h3` at https://github.com/uber/h3/issues/218.

**Comment by grim7reaper** [comment]
Good point!

I had a quick look to see which functions are really Earth-specific, and it far less than what I expected:
1. `getHexagonAreaAvg{Km2,M2}`
2. `getHexagonEdgeLengthAvg{Km,M}`
3. `cellArea{Km2,M2}`
4. `edgeLength{Km,M}`
5. `polygonToCells`

The annoying one is `5`, but from the look of it it can be easily be made planet-independent.

`3` and `4` can be easily derived from the radians version.
Similarly, `1` and `2` could be handled by exposing a radians version.

---

Do you have a use case in mind?
Just trying to gauge how common this would be, to decide on the next move.

I see two paths forward:
- if it's too niche to warrant a built-in support:
    - fix `polygonToCells` to be radius independant
   - add `getHexagonAreaAvgRads2` and `getHexagonEdgeLengthAvgRads` (let user use those to build their planet-flavored version of `getHexagonAreaAvg{Km2,M2}`/`getHexagonEdgeLengthAvg{Km,M}`)
    - nothing to do for `cellArea{Km2,M2}`/`edgeLength{Km,M}` (radians version already exists)
- if it's common enough to deserve a built-in support:
    - fix `polygonToCells` to be radius independant
    - change `getHexagonAreaAvg{Km2,M2}`/`getHexagonEdgeLengthAvg{Km,M}` signature to take an extra parameter (a radius)
    - ditto for `cellArea{Km2,M2}`/`edgeLength{Km,M}`

---

Either way, I'm probably gonna patch `polygonToCells` to be planet-independent.
The only question is about the area/length functions.

**Comment by LegNeato** [comment]
It's probably too niche :-). Use cases:

* Mars a la https://www.google.com/mars/
* Moon a la https://www.google.com/moon/
* Custom planets in games
* Spherical mesh coordinate system to use in games

I also have an untested idea that it might be compelling to represent 3d space with stacking h3 grids of varying radii, like polar coordinates but it would be (R, H3Index)

**Comment by grim7reaper** [comment]
Ok, then I'll go with the first approach.

**Comment by LegNeato** [comment]
Would it be ergonomic for `getHexagonAreaAvg{Km2,M2}/getHexagonEdgeLengthAvg{Km,M}` take a const parameter with a default value of earth

**Comment by grim7reaper** [comment]
Would be a good option, but unfortunately const generics only supports integer types, `bool` and `char`.

So not possible for now, but will keep it in mind for when the support is extended to more types

**Comment by LegNeato** [comment]
Wow that was quick, awesome!
