### ISSUE TITLE
Cannot compile h3o to wasm due to system dependency

### ISSUE THREAD

**Issue by tjhunter** [HydroniumLabs/h3o#9]
Thank you for your great work on `h3o`. 

The `ahash` dependency currently prevents it from compiling to `wasm`, because of its dependency to the OS' random generator. You can see that in `cargo-tree`:

```
├── ahash v0.8.3
│   ├── cfg-if v1.0.0
│   ├── getrandom v0.2.8
│   │   ├── cfg-if v1.0.0
│   │   └── libc v0.2.140
```

My current workaround is to change the `ahash` depency in Cargo.toml to:
```
ahash = { version = "0.8", default-features = false, features = ["std", "compile-time-rng"] }
```

This has some downsides because it makes the build not reproductible without an environment flag, see this doc:
https://github.com/tkaitchuck/constrandom#deterministic-builds

What are your thoughts? Personally, I believe that depending on the OS's system generator for good entropy is not so important, but this is certainly the call of the developers.

**Comment by grim7reaper** [comment]
Thanks for raising this issue.

I'll switch over to compile-time RNG then. I don't really rely on reproducible builds for now, but if I ever need it I can apply the workaround you linked.
If runtime RNG is really needed at some point, I will add a feature to enable it but let's keep thing simple for now.

I've just released a 0.3.1 with the fix.
